

import {
  PieChart, Pie, Cell, BarChart, Bar, XAxis, YAxis, CartesianGrid,
  Tooltip, ResponsiveContainer, Legend, RadarChart, PolarGrid,
  PolarAngleAxis, PolarRadiusAxis, Radar,
} from 'recharts';
import { FileText, FileSpreadsheet, File, Download } from 'lucide-react';
import {
  assetCategoryReport, assetStatusReport,
  departmentAllocationReport, maintenanceFrequencyReport,
  resourceUtilizationReport, recentReports,
} from '../data/reports';
import Breadcrumb from '../../../components/ui/Breadcrumb';
import Card from '../../../components/ui/Card';
import ChartCard from '../../../components/ui/ChartCard';
import Button from '../../../components/ui/Button';
import Table from '../../../components/ui/Table';
import toast from 'react-hot-toast';

const formatIcons = {
  PDF: FileText,
  Excel: FileSpreadsheet,
  CSV: File,
};

export default function Reports() {
  const reportColumns = [
    {
      key: 'name',
      label: 'Report Name',
      render: (val) => <span className="font-medium text-text">{val}</span>,
    },
    { key: 'type', label: 'Type' },
    { key: 'generatedBy', label: 'Generated By' },
    { key: 'date', label: 'Date' },
    { key: 'size', label: 'Size' },
    {
      key: 'format',
      label: 'Format',
      render: (val) => {
        const Icon = formatIcons[val] || File;
        return (
          <div className="flex items-center gap-1.5">
            <Icon className="w-4 h-4 text-muted" />
            <span>{val}</span>
          </div>
        );
      },
    },
    {
      key: 'actions',
      label: '',
      render: () => (
        <button
          onClick={(e) => { e.stopPropagation(); toast.success('Download started'); }}
          className="p-1.5 rounded-lg hover:bg-gray-100 text-muted hover:text-primary transition-colors"
        >
          <Download className="w-4 h-4" />
        </button>
      ),
    },
  ];

  // Transform resource utilization for radar chart
  const radarData = resourceUtilizationReport.map((r) => ({
    resource: r.resource,
    utilization: r.utilization,
    fullMark: 100,
  }));

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-text">Reports & Analytics</h1>
          <Breadcrumb items={[{ label: 'Reports' }]} />
        </div>
        <div className="flex gap-3">
          <Button variant="outline" icon={Download} onClick={() => toast.success('Export initiated')}>
            Export PDF
          </Button>
          <Button icon={FileSpreadsheet} onClick={() => toast.success('Export initiated')}>
            Export Excel
          </Button>
        </div>
      </div>

      {/* Charts Row 1 */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <ChartCard title="Asset Category Distribution" subtitle="Assets grouped by category">
          <ResponsiveContainer width="100%" height={300}>
            <PieChart>
              <Pie
                data={assetCategoryReport}
                cx="50%"
                cy="50%"
                outerRadius={110}
                innerRadius={65}
                paddingAngle={3}
                dataKey="value"
              >
                {assetCategoryReport.map((entry, i) => (
                  <Cell key={i} fill={entry.fill} />
                ))}
              </Pie>
              <Tooltip
                contentStyle={{ borderRadius: '12px', border: 'none', boxShadow: '0 4px 20px rgba(0,0,0,0.08)', fontSize: '13px' }}
              />
              <Legend iconType="circle" iconSize={8} wrapperStyle={{ fontSize: '11px' }} />
            </PieChart>
          </ResponsiveContainer>
        </ChartCard>

        <ChartCard title="Asset Status Overview" subtitle="Current status breakdown">
          <ResponsiveContainer width="100%" height={300}>
            <PieChart>
              <Pie
                data={assetStatusReport}
                cx="50%"
                cy="50%"
                outerRadius={110}
                innerRadius={65}
                paddingAngle={3}
                dataKey="value"
              >
                {assetStatusReport.map((entry, i) => (
                  <Cell key={i} fill={entry.fill} />
                ))}
              </Pie>
              <Tooltip
                contentStyle={{ borderRadius: '12px', border: 'none', boxShadow: '0 4px 20px rgba(0,0,0,0.08)', fontSize: '13px' }}
              />
              <Legend iconType="circle" iconSize={8} wrapperStyle={{ fontSize: '11px' }} />
            </PieChart>
          </ResponsiveContainer>
        </ChartCard>
      </div>

      {/* Charts Row 2 */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <ChartCard title="Department Asset Allocation" subtitle="Asset distribution by department">
          <ResponsiveContainer width="100%" height={300}>
            <BarChart data={departmentAllocationReport}>
              <CartesianGrid strokeDasharray="3 3" stroke="#f0f0f0" />
              <XAxis dataKey="department" fontSize={11} stroke="#6B7280" />
              <YAxis fontSize={11} stroke="#6B7280" />
              <Tooltip
                contentStyle={{ borderRadius: '12px', border: 'none', boxShadow: '0 4px 20px rgba(0,0,0,0.08)', fontSize: '13px' }}
              />
              <Legend iconType="circle" iconSize={8} wrapperStyle={{ fontSize: '11px' }} />
              <Bar dataKey="laptops" fill="#4F46E5" radius={[4, 4, 0, 0]} barSize={14} />
              <Bar dataKey="monitors" fill="#818CF8" radius={[4, 4, 0, 0]} barSize={14} />
              <Bar dataKey="furniture" fill="#10B981" radius={[4, 4, 0, 0]} barSize={14} />
              <Bar dataKey="other" fill="#F59E0B" radius={[4, 4, 0, 0]} barSize={14} />
            </BarChart>
          </ResponsiveContainer>
        </ChartCard>

        <ChartCard title="Maintenance Frequency" subtitle="Monthly breakdown by priority">
          <ResponsiveContainer width="100%" height={300}>
            <BarChart data={maintenanceFrequencyReport}>
              <CartesianGrid strokeDasharray="3 3" stroke="#f0f0f0" />
              <XAxis dataKey="month" fontSize={11} stroke="#6B7280" />
              <YAxis fontSize={11} stroke="#6B7280" />
              <Tooltip
                contentStyle={{ borderRadius: '12px', border: 'none', boxShadow: '0 4px 20px rgba(0,0,0,0.08)', fontSize: '13px' }}
              />
              <Legend iconType="circle" iconSize={8} wrapperStyle={{ fontSize: '11px' }} />
              <Bar dataKey="critical" fill="#DC2626" radius={[4, 4, 0, 0]} barSize={14} stackId="a" />
              <Bar dataKey="high" fill="#F59E0B" radius={[4, 4, 0, 0]} barSize={14} stackId="a" />
              <Bar dataKey="medium" fill="#818CF8" radius={[4, 4, 0, 0]} barSize={14} stackId="a" />
              <Bar dataKey="low" fill="#6B7280" radius={[4, 4, 0, 0]} barSize={14} stackId="a" />
            </BarChart>
          </ResponsiveContainer>
        </ChartCard>
      </div>

      {/* Resource Utilization */}
      <ChartCard title="Resource Utilization" subtitle="Usage rate of shared resources">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          <ResponsiveContainer width="100%" height={280}>
            <RadarChart data={radarData}>
              <PolarGrid stroke="#e5e7eb" />
              <PolarAngleAxis dataKey="resource" fontSize={11} stroke="#6B7280" />
              <PolarRadiusAxis domain={[0, 100]} fontSize={10} stroke="#6B7280" />
              <Radar dataKey="utilization" stroke="#4F46E5" fill="#4F46E5" fillOpacity={0.2} />
            </RadarChart>
          </ResponsiveContainer>
          <div className="space-y-3 flex flex-col justify-center">
            {resourceUtilizationReport.map((resource) => (
              <div key={resource.resource} className="flex items-center gap-3">
                <div className="flex-1">
                  <div className="flex items-center justify-between mb-1">
                    <span className="text-sm font-medium text-text">{resource.resource}</span>
                    <span className="text-sm font-bold text-text">{resource.utilization}%</span>
                  </div>
                  <div className="w-full h-2 bg-gray-100 rounded-full overflow-hidden">
                    <div
                      className="h-full bg-primary rounded-full transition-all duration-1000 ease-out"
                      style={{ width: `${resource.utilization}%` }}
                    />
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </ChartCard>

      {/* Recent Reports Table */}
      <Card hover={false}>
        <div className="flex items-center justify-between mb-4">
          <h3 className="text-sm font-semibold text-text">Recent Reports</h3>
        </div>
        <Table columns={reportColumns} data={recentReports} />
      </Card>
    </div>
  );
}
